services:
  make:
    image: genjiohara/make
    container_name: chess-make
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
  doxygen:
    image: greenbone/doxygen
    container_name: chess-doxygen
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
